
export const DOCUMENT_TEXT = `
Análisis del Paisaje de Ambuqui: Un Estudio Integral de Ecosistemas, Medios de Vida y Vulnerabilidades

1. Caracterización General del Paisaje de Ambuqui
Esta sección establece una comprensión fundamental del paisaje de Ambuqui, detallando sus componentes ecológicos y los sistemas de vida primarios que definen su tejido socioeconómico.

1.1. Sistemas Ecológicos: Tipos, Estado de Salud y su Relación con Medios de Vida y Servicios Ecosistémicos
El paisaje de Ambuqui se distingue por la presencia de ecosistemas variados, distribuidos en diferentes zonas altitudinales: Zona Alta, Zona Media y Zona Baja. La Zona Alta abarca el Bosque montano, el Páramo y el Matorral interandino. La Zona Media se caracteriza por el Bosque espinozo, mientras que la Zona Baja incluye las Riveras del río y también el Bosque espinozo.
La evaluación del estado de salud de estos ecosistemas, utilizando una escala de 1 a 3 (donde 1 indica funcionalidad adecuada, 2 funcionalidad moderada y 3 poca funcionalidad), revela una situación que merece atención. La mayoría de los ecosistemas identificados, como el Bosque montano, el Páramo, el Bosque espinozo (en ambas zonas) y las Riveras del río, exhiben una funcionalidad moderada (valor 2). Esto sugiere que el paisaje no se encuentra en un estado prístino, sino que experimenta presiones crónicas y generalizadas. Un caso particular de preocupación es el Matorral interandino en la Zona Alta, clasificado como poco funcional (valor 3), lo que indica una degradación significativa. Esta disparidad subraya la necesidad de intervenciones que aborden tanto los impactos difusos como la restauración dirigida en áreas altamente deterioradas.
La relación entre estos ecosistemas y los medios de vida locales es intrínseca. Los ecosistemas están directamente vinculados a una amplia gama de actividades productivas. Por ejemplo, el Bosque montano en la Zona Alta sustenta medios de vida como la cría de Cuy, el cultivo de manzana, maíz, claudia, trigo, la cría de borregos, gallinas, cerdos, la ganadería, el cultivo de arveja y los huertos hortícolas. El Páramo es fundamental para la cría de cerdos, borregos, el cultivo de fréjol, gallinas, maíz, trigo, la ganadería, los huertos hortícolas, el chocho y la arveja. En la Zona Media, el Bosque espinozo está asociado con el cultivo de mango, aguacate, limón (cítricos), ovos, la cría de gallinas y el turismo comunitario. Las Riveras del río en la Zona Baja son vitales para las artesanías, el fréjol y la pesca. Esta dependencia directa significa que la salud de los ecosistemas es un determinante directo de la estabilidad económica y la seguridad alimentaria local. La degradación de los ecosistemas, por lo tanto, amenaza directamente la viabilidad de los medios de vida que dependen de ellos.
Los servicios ecosistémicos proporcionados por estos entornos naturales son diversos y esenciales. Se codifican para indicar su tipo, como P para Provisión, R para Regulación, A para Soporte y C para Cultural. Ejemplos específicos de servicios incluyen la provisión de Alimentos para los animales (P1) del Matorral interandino y Agua para consumo humano, animal y para riego (P3) del Páramo y el Bosque montano. La mención recurrente de problemas relacionados con el agua (escasez, contaminación, infraestructura deficiente) en diferentes ecosistemas y frente a diversas amenazas, señala la seguridad hídrica como una vulnerabilidad fundamental y transversal en el paisaje de Ambuqui. Cualquier intervención para mejorar la seguridad de los medios de vida o la salud de los ecosistemas debe priorizar una gestión integrada de los recursos hídricos, abordando tanto la oferta (salud del ecosistema, resiliencia climática) como la demanda (uso eficiente, infraestructura).
Las causas de la degradación de los ecosistemas son variadas y a menudo interconectadas. Las causas comunes observadas en múltiples ecosistemas incluyen la Tala (de árboles), las quemas, el aumento de la frontera agrícola y pecuaria, el uso de agroquímicos y el mal manejo de residuos sólidos. Específicamente para el Bosque espinozo en la Zona Media, se identifican la minería, la deforestación, los incendios forestales y el mal uso del agua de riego como factores de degradación.

Tabla 1.1: Resumen de Ecosistemas, Salud y Servicios Ecosistémicos Clave por Zona
Grupo,Ecosistema,Salud (1=adecuada, 2=moderada, 3=poca),Medios de Vida Relacionados (ejemplos),Servicios Ecosistémicos Clave (códigos),Causas de Degradación (ejemplos)
Zona Alta,Bosque montano,2 (Moderada),"Cuy, manzana, maíz, trigo, ganadería, arveja","P2, P4, A1, R5, A2, P3, R1, R2, R6, C2, R3","Tala, aumento frontera agrícola y pecuaria, uso de agroquímicos, quemas"
Zona Alta,Páramo,2 (Moderada),"Cerdos, borregos, fréjol, maíz, trigo, ganadería","P3, P4, R6, R7, R1, A1, R2, P1","Quemas, aumento frontera agrícola, mal manejo de residuos sólidos"
Zona Alta,Matorral interandino,3 (Poca),"Borregos, ganadería, gallinas, cuyes","R6, R5, R2, A2, P2, R7, R3, P4, P1","Quemas, aumento frontera agrícola y pecuaria, uso de agroquímicos, extracción de leña"
Zona Media,Bosque espinozo,2 (Moderada),"Mango, aguacate, limón, ovos, gallinas, turismo comunitario","P4, A2, R2, P1, C1, C2, R1, R6, R5, P2, R3, A1, R7","Aumento frontera agrícola, uso de insecticidas y herbicidas, minería, deforestación, incendios forestales"
Zona Baja,"Riveras del río",2 (Moderada),"Artesanías, fréjol, peces","P3, R1, R5, R4, P1, A1, P2","Tala, quemas, contaminación fuentes hídricas"
Zona Baja,Bosque espinozo,2 (Moderada),"Mango, aguacate, fréjol, limón, flor de jamaica, pimiento","A2, A1, R2, K3, R6, R5","Tala, uso de maquinaria agrícola, quema, contaminación"

1.2. Medios de Vida Principales: Sistemas Productivos, Tamaños, Tenencias Dominantes y Cadenas de Valor
El paisaje de Ambuquí se caracteriza por una amplia y diversa gama de medios de vida, que varían significativamente según la zona altitudinal. En la Zona Alta, predominan la agricultura y la ganadería tradicionales, con cultivos como Maíz, Trigo y Arveja, y la crianza de Gallinas, Borregos y Ganadería. La Zona Media presenta una combinación de fruticultura (Mango, Aguacate, Ovo, Limón), avicultura (Gallinas) y el desarrollo de sectores emergentes como el Turismo comunitario. Por su parte, la Zona Baja se distingue por una horticultura y fruticultura variada, incluyendo Fréjol, Pimiento, Mango, Limón, Flor de Jamaica y Aguacate, además de Turismo comunitario y artesanías.
Una característica distintiva de muchos de estos medios de vida es su doble propósito: autoconsumo y comercial. Esta estrategia dual se observa en una amplia gama de productos como Arveja, Maíz, Manzana, Fréjol, Gallinas, Cuyes, Habas, Tomate Riñón, Trigo, Cebada, Mango, Limón, Peces, Ovos, Mandarina, Guabas, Cerdos, Huertos Hortícolas, Guandul, Papaya, Guayaba, Aguacate, Camote, Verde o maduro, Yuca, Maíz Morocho, Plátano Seda, Pimiento, Yuca Camote, Pepinillo, Cebolla Paiteña, Tomate, Jamaica y Sandía. Esta combinación de producción de subsistencia para la seguridad alimentaria y actividades comerciales para la generación de ingresos puede mejorar la resiliencia de los hogares, pero también los expone a riesgos tanto ambientales como de mercado. Otros medios de vida, como la Ganadería y los Borregos en la Zona Alta, y el Turismo comunitario, las Artesanías y la Caña de Azúcar en la Zona Media y Baja, son predominantemente comerciales.
Los productos finales derivados de estos sistemas productivos abarcan desde bienes agrícolas en bruto, como Maíz en grano o Arveja tierna y seca, hasta productos procesados de mayor valor añadido, como harinas, machica, pulpa, helados, mermeladas, vino, jugos y fruta deshidratada. Estos productos se comercializan en diversos mercados: local, regional, nacional y de exportación. Por ejemplo, los productos de la Zona Alta como Maíz, Trigo, Arveja, Ganadería, Borregos y Gallinas se destinan principalmente a mercados local y regional. En contraste, medios de vida de la Zona Media como el Turismo comunitario, Ovos, Aguacate, Limón y Mango muestran una mezcla de mercados local, nacional y de exportación (particularmente para Aguacate y Mango). Los productos de la Zona Baja, como Fréjol, Pimiento, Mango, Limón, Flor de Jamaica y Aguacate, se dirigen a mercados local y nacional, con cierto potencial de exportación para el Mango. La importancia de estos medios de vida para la generación de ingresos, medida en una escala de 1 a 3, es generalmente alta, con la mayoría de los medios de vida priorizados calificados con 2 o 3, lo que subraya su relevancia económica para las familias del paisaje.
En cuanto a los tamaños y tenencias dominantes, la estructura productiva de Ambuqui se caracteriza por la coexistencia de diferentes escalas. Las propiedades se clasifican en pequeño, mediano y grande, con rangos de área específicos (por ejemplo, Ha, m2, Individuos). La categoría pequeño es a menudo la predominante para muchos medios de vida, como Maíz, Trigo, Arveja, Ganadería, Borrego y Gallinas en la Zona Alta, o Turismo comunitario, Ovos, Aguacate, Limón y Mango en la Zona Media, y Flor de Jamaica en la Zona Baja, representando entre el 50% y el 80% de los productores. Sin embargo, las propiedades de tamaño mediano y grande también representan porcentajes significativos para algunos medios de vida, especialmente en la Zona Baja, donde el Fréjol y el Pimiento tienen un 50% de su producción en propiedades grande.
Las tenencias de la tierra incluyen Propio (con título de propiedad), Herencia (adquirida por sucesión), Posesión (uso sin título legal), Arriendo (alquiler) y Al Partir (aparcería). Las formas de tenencia Propio y Herencia son comunes en todas las zonas. No obstante, la Posesión es notablemente alta en la Zona Alta, especialmente para pequeños productores de Maíz, Trigo, Arveja, Ganadería, Borregos y Gallinas, donde representa hasta el 50% para propiedades pequeñas. Las modalidades de Arriendo y Al Partir son relevantes en la Zona Media (Turismo comunitario, Ovos) y en la Zona Baja (Fréjol, Pimiento). Para el Fréjol y el Pimiento en la Zona Baja, el Arriendo y el Al Partir combinados representan el 70% de las propiedades pequeñas y medianas, y el 70% de las grandes. La prevalencia de la Posesión, el Arriendo y el Al Partir para una parte significativa de la población, especialmente pequeños productores, implica una inseguridad en la tenencia de la tierra. Esta falta de título formal puede limitar el acceso a crédito, la inversión en mejoras del terreno y la participación en cadenas de valor formales, lo que aumenta la vulnerabilidad de estos medios de vida.

2. Caracterización por Medio de Vida y Análisis de Servicios Ecosistémicos
Esta sección profundiza en el análisis de los aspectos de seguridad humana relacionados con los medios de vida y detalla los servicios ecosistémicos críticos que los sustentan, incluyendo aquellos bajo amenaza.

2.1. Niveles de Seguridad Humana, Migración, Remesas y Equidad por Medio de Vida
El análisis de los impactos de las amenazas en las dimensiones de la seguridad humana revela una erosión multidimensional. Amenazas como la Sequía, ya sea en la Zona Alta, Media o Baja, afectan a medios de vida como Maíz, Trigo y Arveja o Aguacate, Limón, resultando en una pérdida total de ingresos económicos y escasez generalizada de alimentos. La Contaminación basurero en la Zona Baja provoca la Pérdida de fuentes de empleo por el mal olor y la Contaminación de los alimentos por lixiviados. Estos ejemplos ilustran cómo una sola amenaza puede tener repercusiones en cascada, afectando la seguridad económica, alimentaria, sanitaria, ambiental, personal, comunitaria y política. Esta interconexión significa que abordar una dimensión de forma aislada es insuficiente; se requiere un enfoque holístico para la seguridad humana.
En el ámbito de la seguridad sanitaria, los impactos varían desde Pocos casos de problemas de salud en el ámbito respiratorio asociados a la sequía, hasta Problemas respiratorios por el humo causados por las quemas, y un Aumento de la presencia de insectos tras el desbordamiento de ríos. La Contaminación basurero se asocia con la Presencia de roedores en cultivos y hogares y Problemas frecuentes de salud como problemas gastrointestinales. La seguridad ambiental se ve comprometida por el deterioro en los servicios ecosistémicos, la Pérdida de los servicios ecosistémicos, el Aumento de los procesos erosivos y la Contaminación directa al ambiente. A nivel personal, se observa una Percepción de inseguridad y un Aumento de robos de los productos debido a la sequía.
En cuanto a la seguridad comunitaria, los conflictos son frecuentes, como los Conflictos por el recurso agua a causa de la sequía y las Tensiones leves entre vecinos por competencia de recursos naturales debido al cambio de uso de suelo. La Contaminación basurero ha llevado a Enfrentamientos entre miembros de la comunidad y autoridades. La seguridad política se ve afectada por Restricciones menores en el acceso a recursos, Debilidad en la gobernanza local y la percepción de que No hay atención oportuna por las autoridades.
Respecto a la migración y la dependencia de remesas, la información directa sobre los niveles de migración o la dependencia de remesas no se encuentra explícitamente en los datos proporcionados. Sin embargo, la Migración y desplazamientos forzados se identifica como un tipo de conflicto vinculado a la Sequía que afecta a medios de vida como Aguacate y Limón en la Zona Media, y al servicio ecosistémico P1 en la Zona Alta. Esto sugiere que, si bien no se cuantifican los flujos migratorios, las amenazas severas pueden desencadenar desplazamientos forzados o la migración como mecanismo de adaptación. La migración, por lo tanto, no es un problema aislado, sino una posible consecuencia o estrategia de afrontamiento ante los impactos compuestos de las amenazas ambientales y climáticas en la seguridad humana. Abordar las causas fundamentales de la degradación ambiental y la vulnerabilidad climática es esencial para prevenir la migración forzada y promover la estabilidad en el paisaje de Ambuqui.
En términos de equidad, la columna i_diferenciado indica que Hombres, mujeres, jóvenes, grupos marginados son generalmente afectados por la mayoría de las amenazas, lo que sugiere una vulnerabilidad generalizada en la comunidad. Sin embargo, los comentarios cualitativos en la columna incl_descripcion de 3.5. SE y MdV.csv ofrecen una visión más matizada sobre la equidad en los beneficios de los servicios ecosistémicos. Por ejemplo, para la provisión de agua en la Zona Alta, se indica que Todos se benefician por igual. En contraste, para la provisión de alimentos silvestres en la Zona Media, se señala que Las mujeres son las que se encargan en las actividades de cosecha, lo que implica un rol y un beneficio específicos de género. De manera similar, en la apicultura, Los hombres son los que realizan las actividades de apicultura, indicando una actividad dominada por hombres. Para la materia orgánica y los microorganismos de montaña, Los hombres realizan las actividades físicas, mujeres y jóvenes apoyan a la producción, mostrando una división de trabajo por género. Esta información revela que los beneficios de los servicios ecosistémicos no siempre se distribuyen equitativamente. Las funciones de género en la recolección o gestión de servicios específicos implican que las amenazas a estos servicios podrían afectar desproporcionadamente a grupos específicos, incluso si el impacto general se describe como amplio. Las evaluaciones de vulnerabilidad deben ir más allá de los números agregados y profundizar en los roles y responsabilidades de los diferentes grupos sociales para identificar y abordar estos impactos diferenciados de manera efectiva.

2.2. Servicios Ecosistémicos que Sostienen los Medios de Vida Priorizados
Los servicios ecosistémicos son fundamentales para la viabilidad de los medios de vida priorizados en Ambuqui, existiendo vínculos explícitos entre ellos. La provisión de agua (P3) es un servicio crítico para Maíz, ganadería, trigo, arveja, borregos, gallinas en la Zona Alta, y para Fréjol y peces en la Zona Baja, cubriendo necesidades humanas, animales y de riego. Esta interdependencia a lo largo de las zonas demuestra que el paisaje de Ambuqui funciona como un sistema interconectado, donde la salud de los ecosistemas en una zona (por ejemplo, la regulación del agua en la Zona Alta) influye directamente en la viabilidad de los medios de vida y las comunidades en otras zonas (por ejemplo, la agricultura en la Zona Baja). Esto subraya la necesidad de un enfoque de gestión a escala de paisaje, en lugar de intervenciones zonales aisladas.
La provisión de alimentos (P1) también es vital. El Matorral interandino proporciona Alimentos para los animales para Borregos, ganadería, gallinas y cuyes en la Zona Alta. En la Zona Media, el Bosque espinozo provee alimentos silvestres como tuna, guandul y pitahaya para medios de vida como Aguacate, mango y ovos. Además, el Bosque espinozo en la Zona Media contribuye a la regulación de la fertilidad del suelo (R5) al proveer materia orgánica y microorganismos de montaña para cultivos como Aguacate, mango, ovos y limón. Este mismo ecosistema también apoya la polinización (R6) para Mango, aguacate y ovos, lo que resulta en la producción de miel, polen y cera.
La provisión de materias primas (A1, P2) es otro servicio esencial. Las Riveras del río en la Zona Baja ofrecen insumos de tutoreo para Fréjol y artesanías. Asimismo, el Bosque espinozo en la Zona Baja proporciona leña y carbón para medios de vida como Limón, mango, flor de jamaica, aguacate y pimiento. Finalmente, el Bosque espinozo en la Zona Baja también es una fuente de recursos medicinales (P4), proveyendo plantas medicinales para Limón y flor de jamaica. La multifuncionalidad de los ecosistemas individuales, que proporcionan un conjunto de servicios que sustentan colectivamente diversos medios de vida, significa que la degradación de un solo ecosistema puede tener impactos negativos en cascada en múltiples sectores productivos.

2.3. Servicios Ecosistémicos Amenazados: Disminución, Aumento de Demanda y Causas
Los servicios ecosistémicos en Ambuqui están bajo una presión considerable, enfrentando amenazas que resultan en la disminución de su provisión, interrupciones en su flujo o un aumento en su demanda. La provisión de agua (P3) es particularmente vulnerable. Disminuye debido al aumento de quemas y talas en el Páramo, al aumento de la sequía y presencia de actividades de deforestación en el Bosque montano, y a la reducción del caudal de agua en los ríos y vertientes en las Riveras del río. La provisión de alimentos (P1), específicamente los alimentos silvestres, disminuye debido al aumento de la frontera agrícola y al cambio de uso de suelo en el Bosque espinozo de la Zona Media. La polinización (R6) se ve afectada por el uso inadecuado de insecticidas en el Bosque espinozo de la Zona Media. La fertilidad del suelo (R5) también disminuye debido al cambio de uso de suelo y a la mecanización inadecuada de los suelos en el Bosque espinozo de la Zona Media. Las materias primas (A1, P2) de las Riveras del río disminuyen mediante la construcción de viviendas y el cambio de cultivos de ciclo corto a permanentes. La obtención de leña del Bosque espinozo (Be_P2) se complica por la obtención de los permisos necesarios.
Además de la disminución en la provisión, existen interrupciones en el flujo o acceso a estos servicios. El acceso al agua (P3) se complica por la deficiente infraestructura y falta de mantenimiento en el Páramo y la poca infraestructura de distribución en el Bosque montano. El acceso a los servicios de polinización (R6) se ve dificultado por la falta de asesoría y manejo técnico. Estas barreras de infraestructura y capacidad técnica actúan como impedimentos significativos para el flujo efectivo y el acceso de los usuarios a los servicios ecosistémicos, incluso donde el potencial de provisión existe. Esto indica que la protección de los ecosistemas por sí sola no es suficiente; la inversión en infraestructura y capital humano es igualmente crucial.
La demanda de algunos servicios ecosistémicos, como el agua (P3), aumenta ya que se benefician las personas, animales y cultivos del territorio. Los comentarios cualitativos también resaltan problemas como la mayor carga animal en el Matorral interandino y la necesidad de permisos de corte al MAATE para la madera. Las presiones sobre los servicios ecosistémicos en Ambuqui son una combinación de actividades humanas directas (cambio de uso de suelo, uso de agroquímicos, quemas, tala) y factores climáticos (sequía), que a menudo se refuerzan mutuamente, llevando a un declive acumulativo. Comprender las vulnerabilidades estacionales, como los meses de escasez de bienes ecosistémicos (por ejemplo, de mayo a octubre para alimentos de animales del Matorral interandino o de enero a febrero para el agua de las Riveras del río), es fundamental para diseñar estrategias de planificación y resiliencia que se adapten a estos patrones predecibles de escasez.

3. Distribución Espacial de Elementos Clave del Paisaje
Esta sección describe la distribución espacial de los ecosistemas, servicios, amenazas y medios de vida, enfatizando la importancia de la comprensión espacial para una gestión integrada del paisaje.

3.1. Distribución de Ecosistemas y su Salud
La distribución de los ecosistemas en Ambuqui sigue un patrón zonal claro. El Páramo, el Bosque Montano y el Matorral Interandino se encuentran en la Zona Alta. El Bosque Espinozo predomina en la Zona Media, y en la Zona Baja se localizan las Riveras del Río y también el Bosque Espinozo. Al mapear estos ecosistemas, se podría visualizar su ubicación y extensión dentro del paisaje.
La salud de cada ecosistema, indicada por el valor es_salud, también se representaría espacialmente. Por ejemplo, el Matorral interandino en la Zona Alta, con un valor de 3 (poco funcional), se destacaría como un área de degradación significativa. Esta representación espacial revelaría que la degradación de los ecosistemas no es uniforme. Zonas como el Matorral interandino en la Zona Alta constituyen focos críticos de degradación, probablemente debido a presiones concentradas de la expansión agrícola y ganadera, y las quemas. La focalización espacial de los esfuerzos de conservación y restauración en estos puntos críticos podría generar beneficios desproporcionadamente altos para la salud general del paisaje y la provisión de servicios ecosistémicos.

3.2. Distribución de Servicios Ecosistémicos y sus Usuarios
La distribución de los servicios ecosistémicos, como la provisión de agua, alimentos o polinización, se alinea con la ubicación de los ecosistemas que los originan. Por ejemplo, el agua del Páramo y el Bosque montano en la Zona Alta beneficia a 400 usuarios en esa misma zona. Sin embargo, el agua de las Riveras del río en la Zona Baja beneficia a un número mayor de usuarios (800 familias) en comunidades como El Chota, San Alfonso de Ambuqui, Carpuela, Juncal - Chalguayacu.
Un mapeo de estos servicios y sus usuarios destacaría que, si bien algunos servicios ecosistémicos son localizados, otros, como el agua, tienen un alcance espacial amplio, beneficiando a comunidades distantes de su fuente. Esto crea una interdependencia donde la gestión de la tierra en las zonas altas impacta directamente la disponibilidad de recursos para los usuarios en las zonas bajas. Esta visualización espacial reforzaría la necesidad de una gestión integrada de cuencas hidrográficas y una cooperación interjurisdiccional, ya que las acciones en una parte del paisaje tienen efectos en cascada sobre la disponibilidad de recursos y la seguridad en otras.

3.3. Distribución de Amenazas sobre Servicios Ecosistémicos
Las amenazas climáticas y no climáticas se distribuirían espacialmente según los sitios afectados. Por ejemplo, la Sequía en la Zona Alta afecta a Peñaherrera y Rumipamba, identificados con los códigos Se1, Se2. Las Quemas impactan a Rumipamba, Chaupi Gurangui, Peñaherrera, con códigos Q1, Q2, Q3. El Relleno sanitario en la Zona Baja afecta a Espadillas, San Alfonso, El Refugio, Bermejal, Ramal, Chota, con el código Acbs.
El mapeo de estas amenazas, diferenciando entre las de origen climático y no climático, permitiría identificar áreas donde múltiples amenazas se superponen. Por ejemplo, Peñaherrera y Rumipamba en la Zona Alta se ven afectados tanto por la Sequía como por las Quemas. Esta superposición de amenazas crea vulnerabilidades compuestas, donde el impacto de una amenaza se ve exacerbado por la presencia de otras. Las estrategias de gestión de riesgos integradas son esenciales en estos focos de múltiples peligros.

3.4. Distribución de Medios de Vida (Tipo, Tamaño y Tenencia Dominante)
La distribución de los tipos de medios de vida se corresponde con las zonas altitudinales. Por ejemplo, el cultivo de Maíz predomina en la Zona Alta, mientras que el Mango y el Limón son más relevantes en las Zonas Media y Baja.
El mapeo también representaría los tamaños dominantes y los tipos de tenencia para cada medio de vida. Por ejemplo, el Maíz en la Zona Alta es predominantemente de tamaño pequeño (50%) y se asocia con la tenencia por Posesión (50% para propiedades pequeñas). En contraste, el Fréjol en la Zona Baja presenta una proporción significativa de propiedades grandes (50%) y una alta incidencia de tenencia por Arriendo y Al Partir (70% for todos los tamaños). La representación espacial de estas características de los medios de vida revelaría perfiles de vulnerabilidad socioeconómica distintos en cada zona. Por ejemplo, la dependencia de la Zona Alta de la agricultura a pequeña escala y con tenencia informal podría indicar una mayor vulnerabilidad a los choques y una capacidad de inversión limitada. Las intervenciones, por lo tanto, deben ser espacialmente diferenciadas y adaptadas a los contextos socioeconómicos y de tenencia de la tierra específicos de cada zona.

4. Impactos Actuales de las Amenazas
Esta sección ofrece un análisis detallado de cómo las amenazas climáticas y no climáticas están impactando actualmente la seguridad humana en Ambuqui, identificando tendencias y grupos vulnerables.

4.1. Análisis de Impactos de Amenazas en las Dimensiones de la Seguridad Humana
Las amenazas en Ambuqui generan impactos multidimensionales que afectan diversas esferas de la seguridad humana. La Sequía, una amenaza climática recurrente, impacta severamente medios de vida como Maíz, Trigo y Arveja en la Zona Alta y Aguacate, Limón en la Zona Media, resultando en una pérdida total de ingresos económicos y escasez generalizada de alimentos. A nivel ambiental, se observa un leve deterioro en los servicios ecosistémicos, y a nivel comunitario, provoca Conflictos por el recurso agua. La omnipresencia de los impactos relacionados con el agua, tanto por escasez como por exceso, subraya que el agua es el recurso más crítico y el factor de vulnerabilidad más importante en todo el paisaje, afectando consistentemente múltiples dimensiones de la seguridad humana.
Las Quemas, una amenaza no climática, afectan la Ganadería y los Borregos en la Zona Alta, causando un Aumento insostenible de gastos, Dificil acceso a alimentación animal, Problemas respiratorios y la Pérdida de los servicios ecosistémicos, además de generar una Percepción de inseguridad. El Desbordamiento de río, una amenaza climática en la Zona Baja, impacta cultivos como Pimiento, Flor de Jamaica, Fréjol, provocando pérdidas económicas, la Reducción del acceso a la canasta básica, un Aumento de la presencia de insectos y el Aumento de los procesos erosivos en las riberas.
Un problema significativo es la Contaminación basurero, una amenaza no climática que afecta a múltiples medios de vida en la Zona Baja. Esta amenaza genera Pérdida de fuentes de empleo por el mal olor, Contaminación de los alimentos por lixiviados, Presencia de roedores en cultivos y hogares, Contaminación directa al ambiente y Conflictos locales con las autoridades. Las amenazas no climáticas, a menudo derivadas de una gobernanza deficiente, prácticas insostenibles o una gestión de residuos inadecuada, son importantes impulsores de conflictos localizados y problemas agudos de salud y medio ambiente. Estas son, con frecuencia, más directamente atribuibles a la acción humana y a fallas de gobernanza que los eventos climáticos.
El Cambio de uso de suelo, otra amenaza no climática, afecta al Mango en la Zona Media, llevando a la Pérdida de los cultivos nativos, un Aumento leve del precio de los cultivos nativos, la Pérdida de servicios ecosistémicos y un Aumento de conflictos legales por actividades de cambios de uso de suelo. Los comentarios cualitativos, como "Si la sequía es prolongada existe la pérdida total de ingresos económicos" o "Contaminación directa al ambiente producto de los fuertes olores y lixiviados que contaminan al suelo y fuentes hídricas", ofrecen un contexto crucial y profundizan la comprensión de estos impactos.

4.2. Tendencias de Amenazas y su Impacto en el Número de Familias
El análisis de las tendencias de las amenazas revela que algunas de las más impactantes están en aumento. La Sequía en la Zona Media, por ejemplo, muestra una tendencia de 2, lo que indica un incremento significativo en los últimos años. Otras amenazas con una tendencia de 1, señalando un aumento, incluyen las Heladas (Zona Media), la Deforestación (Zona Media), las Olas de calor (Zona Baja), el Relleno sanitario (Zona Baja), la Contaminación de agua (Zona Baja) y el Uso inadecuado de agroquímicos (Zona Baja). Por otro lado, Crecidas torrenciales (Zona Media) y Quemas (Zona Alta) muestran una tendencia de -1 (disminución), y el Desbordamiento del río (Zona Baja) se mantiene estable con una tendencia de 0.
En cuanto al número de familias afectadas, la Sequía es la amenaza que consistentemente impacta al mayor número de familias, afectando a 400 familias en la Zona Alta (tanto en medios de vida como en servicios ecosistémicos) y a 800 familias en la Zona Baja (en servicios ecosistémicos). La Contaminación basurero impacta a 400 familias en la Zona Baja, y las Quemas afectan a 400 familias en la Zona Alta. El Desbordamiento de río afecta a 160 familias en la Zona Baja, mientras que el Cambio de uso de suelo impacta a 20 familias en la Zona Media.
El paisaje de Ambuqui se enfrenta a un desafío complejo: las amenazas más extendidas en su impacto, como la Sequía, son también las que muestran una tendencia creciente en frecuencia o intensidad. Esto sugiere una vulnerabilidad en aumento y la posibilidad de que futuras crisis afecten a una proporción aún mayor de la población. La priorización de las intervenciones debe centrarse en aquellas amenazas que son tanto generalizadas en su impacto como crecientes en su tendencia, ya que representan los riesgos más urgentes y escalonados para la seguridad humana. Es importante señalar que la "suma" de magnitud, frecuencia y tendencia de una amenaza no siempre se correlaciona directamente con el número de familias impactadas. Algunas amenazas, aunque percibidas como menos intensas o frecuentes, pueden afectar a un gran número de familias debido a su naturaleza (por ejemplo, la degradación generalizada de recursos). Por el contrario, amenazas muy intensas pero localizadas podrían afectar a menos familias. Esto implica que la planificación de intervenciones debe considerar tanto las características intrínsecas de la amenaza como la escala de la exposición humana para una respuesta equilibrada y efectiva.

4.3. Interrelación de Impacto con Servicios Ecosistémicos y Amenazas a los Ecosistemas
Existe una interrelación profunda entre las amenazas, sus impactos en los medios de vida y la salud y provisión de los servicios ecosistémicos, a menudo manifestándose en bucles de retroalimentación. La Sequía, una amenaza climática, no solo impacta directamente a medios de vida como Maíz, Trigo y Arveja, sino que también afecta servicios ecosistémicos clave como la provisión de alimentos (P1) y agua (P3) de los ecosistemas, lo que se traduce en una Disminución del caudal de agua y la necesidad de tratamiento para mejorar la fertilidad del suelo. De manera similar, las Quemas, una amenaza no climática, afectan a la Ganadería y los Borregos, y conducen a la Pérdida de los servicios ecosistémicos, la Erosión de suelos (P1) y la Contaminación producto de la ceniza en las fuentes hídricas (P3).
El Cambio de uso de suelo, otra amenaza no climática, impacta el cultivo de Mango y resulta en la Pérdida de servicios ecosistémicos y un Aumento de plagas y enfermedades en los cultivos (R5 - fertilidad del suelo). Esto se vincula directamente con las barreras para la provisión de alimentos silvestres (Be_P1) y la fertilidad del suelo (Be_R5) en 3.5. SE y MdV.csv. La Contaminación basurero, también una amenaza no climática, afecta a múltiples medios de vida y causa Contaminación directa al ambiente, lo cual es consistente con la Contaminación de agua y su impacto en la provisión de leña/carbón (P2) debido al mal manejo de agroquímicos.
El paisaje de Ambuqui se caracteriza por bucles de retroalimentación que se refuerzan mutuamente. Las prácticas insostenibles de los medios de vida, como la expansión agrícola, las quemas o el uso inadecuado de insecticidas, degradan los ecosistemas y sus servicios. Esta degradación, a su vez, hace que los medios de vida sean más vulnerables a las amenazas climáticas y no climáticas, lo que conduce a impactos más severos y, potencialmente, a la perpetuación de prácticas insostenibles. Las soluciones deben romper estos ciclos negativos, promoviendo prácticas que mejoren los servicios ecosistémicos en lugar de degradarlos, y construyendo resiliencia climática en los sistemas agrícolas y de gestión de recursos.
Existe un vínculo claro entre el uso de agroquímicos, la contaminación del agua (incluida la de los vertederos) y la salud pública. El Uso inadecuado de agroquímicos es una amenaza no climática en aumento, y la Contaminación de agua tiene impactos en la provisión de servicios ecosistémicos y en la salud, como Problemas frecuentes de salud como problemas gastrointestinales. La Contaminación basurero también menciona explícitamente lixiviados que contaminan al suelo y fuentes hídricas. La degradación de los servicios ecosistémicos relacionados con el agua debido a la contaminación tiene implicaciones directas para la salud humana y la calidad de los productos agrícolas. Esto resalta una crisis de salud pública directamente vinculada a fallas en la gestión ambiental, particularmente en la calidad del agua.

4.4. Identificación de Grupos Vulnerables a Impactos Climáticos y No Climáticos
La columna i_diferenciado en los datos de impactos indica consistentemente que Hombres, mujeres, jóvenes, grupos marginados son afectados por la mayoría de las amenazas, lo que sugiere una vulnerabilidad generalizada en toda la comunidad. Sin embargo, los comentarios cualitativos de 3.5. SE y MdV.csv proporcionan una perspectiva más matizada sobre los impactos diferenciados.
Por ejemplo, se observa que Las mujeres son las que se encargan en las actividades de cosecha de alimentos silvestres (Be_P1, Zona Media). Esto implica que las mujeres podrían verse desproporcionadamente afectadas por amenazas que impacten este servicio, como el Cambio de uso de suelo. De manera similar, Los hombres son los que realizan las actividades de apicultura (Be_R6, Zona Media), sugiriendo que los hombres serían los más afectados por amenazas a la polinización, como el uso inadecuado de insecticidas. En el caso de la producción de materia orgánica y microorganismos (Be_R5, Zona Media), Los hombres realizan las actividades físicas, mujeres y jóvenes apoyan a la producción, lo que indica una división del trabajo por género que podría llevar a impactos diferenciados si tareas específicas se ven comprometidas.
Aunque la información cuantitativa a menudo agrupa a todas las categorías vulnerables, los comentarios cualitativos revelan vulnerabilidades específicas, a menudo "invisibles", ligadas a los roles de género en la gestión de recursos y las actividades de subsistencia. Los impactos sobre estas actividades específicas pueden tener efectos desproporcionados en el bienestar y la seguridad de grupos de género particulares. Las evaluaciones de vulnerabilidad deben ir más allá de los números agregados y profundizar en los roles y responsabilidades específicos de los diferentes grupos sociales para identificar y abordar eficazmente estos impactos diferenciados.

5. Dinámicas de Conflictos en el Paisaje
Esta sección analiza la evolución, los impulsores y los actores involucrados en los conflictos dentro del paisaje de Ambuqui, vinculándolos con las amenazas y las vulnerabilidades de los medios de vida.

5.1. Línea de Tiempo de Eventos de Conflicto y Factores de Tensión
La evolución de los conflictos en Ambuqui muestra una transición de la cooperación a la tensión, particularmente en torno a la gestión del agua. Los primeros eventos, como la 1era. concesión de agua de riego en 1975 y la Concesión de agua para consumo humano en 1980, se caracterizaron por una alta cooperación (cooperación = 1), impulsada por la Necesidad de agua y la Unión de la población por necesidad. Esto demuestra que las necesidades básicas compartidas inicialmente fomentaron la acción colectiva.
Sin embargo, a partir del año 2000, comenzaron a surgir tensiones. Un conflicto en el páramo por contaminación por el pisoteo del ganado y conflicto por distribución del agua de riego marcó un punto de inflexión, con diferencias de -1 debido al Daño a fuentes hídricas por contaminación y deforestación. Las dinámicas se volvieron mixtas entre 2004 y 2009, con la Creación de juntas de agua y la Construcción de tanques de reserva en 2004, que, aunque mostraron pugna en la administración, también vieron la Participación de mingas comunitarias. Las Mingas de reforestación e Iniciativas de riego tecnificado en 2009 revelaron Costos altos de los insumos como factor de diferencia, pero también Cooperación entre comunidades, GAD parroquial, MAATE, prefectura.
La escalada de conflictos se hizo más evidente entre 2020 y 2025. En 2020, Rancho Chico impide entrar al páramo, lo que generó un Conflicto de intereses por la administración del páramo, resultando en una suma neta de conflicto de -1. Ese mismo año, la separación de Ambuqui y San Clemente en la administración del agua debido a Conflictos entre directivas de juntas de agua e Intereses personales llevó a una alta conflictividad (suma de -2). Para 2025, la Falta de agua para consumo humano debido a daños en los tanques de reserva y aumento de la población, junto con la Falta de mantenimiento de infraestructura y falta de pago por el servicio, culminó en una suma de -2.
Los factores que influyen en la tensión incluyen Conflicto de intereses por la administración del páramo, Daño a fuentes hídricas por contaminación y deforestación, Pugna en la administración entre instituciones públicas y comunitarias, Costos altos de los insumos, Conflictos entre directivas de juntas de agua, Intereses personales, Falta de mantenimiento de infraestructura, Falta de pago por el servicio, Falta de gestión del GAD parroquial, Poca seriedad de las autoridades y Falta de cumplimiento de autoridades. Estos elementos, predominantemente relacionados con la gobernanza, son los principales impulsores de la escalada y persistencia de los conflictos.
Los factores de cooperación incluyen la Necesidad de agua, la Unión de la población por necesidad, la Incursión de instituciones gubernamentales y no gubernamentales, la Participación de mingas comunitarias con apoyo de ONGs y la Firma de acuerdos compromiso. Aunque el apoyo externo puede fomentar temporalmente la cooperación, la ausencia de estructuras de gobernanza internas sólidas y voluntad política permite que los conflictos resurjan y se intensifiquen.

5.2. Relación entre Amenazas (Climáticas y No Climáticas) y Conflictos
Existe una relación directa y significativa entre las amenazas, tanto climáticas como no climáticas, y la emergencia o exacerbación de conflictos en Ambuqui, impactando directamente los medios de vida y los servicios ecosistémicos.
Las amenazas climáticas son un catalizador fundamental de conflictos. La Sequía está explícitamente vinculada a la Competencia por recursos naturales, la Falta de comunicación y colaboración entre actores, las Instituciones frágiles o ineficientes, y la Migración y desplazamientos forzados. Estos conflictos, a menudo de nivel grave o moderado, surgen de la escasez de recursos, particularmente el agua, que es vital para los medios de vida agrícolas y ganaderos. La Sequía reduce el caudal de agua y limita la producción de alimentos, lo que lleva a tensiones por el acceso al recurso. El Desbordamiento de río también se asocia con la Competencia por recursos naturales, ya que las pérdidas de cultivos y la alteración de la infraestructura hídrica intensifican la disputa por los recursos restantes.
Las amenazas no climáticas, por su parte, son importantes generadoras de conflictos, a menudo arraigadas en problemas de gobernanza y gestión de recursos. Las Quemas se vinculan con Instituciones frágiles o ineficientes, ya que la pérdida de servicios ecosistémicos y la contaminación del agua por cenizas afectan directamente a los medios de vida ganaderos y agrícolas. El Cambio de uso de suelo genera Competencia por recursos naturales y Marginalización, tensión comunitaria o disturbios sociales. Este tipo de conflicto surge de la pérdida de cultivos nativos y servicios ecosistémicos, lo que puede llevar a conflictos legales y tensión leve entre vecinos por la competencia de recursos naturales.
La Contaminación basurero y la Contaminación de agua son fuentes significativas de conflictos relacionados con la Marginalización, tensión comunitaria o disturbios sociales, la Falta de comunicación y colaboración entre actores y las Instituciones frágiles o ineficientes. La contaminación directa del ambiente por lixiviados y olores, junto con la presencia de roedores, afecta la seguridad alimentaria y sanitaria, generando Conflictos locales con las autoridades y enfrentamientos entre la comunidad y las autoridades debido a la falta de atención oportuna. El Uso inadecuado de agroquímicos también se relaciona con Conflictos entre comunidades por la gestión y manejo del agua.
En esencia, la escasez de recursos y la degradación ambiental actúan como disparadores centrales de conflictos. La competencia por recursos cada vez más escasos, especialmente el agua, y la degradación de los ecosistemas que sustentan los medios de vida, alimentan directamente las tensiones. Las amenazas inducidas por el ser humano, a menudo vinculadas a deficiencias en la gobernanza y la gestión, conducen directamente a la inestabilidad social e institucional. Si los conflictos están relacionados con los servicios ecosistémicos, se observa una vinculación directa con las tendencias de provisión y demanda. Por ejemplo, la disminución del caudal de agua debido a la sequía o la contaminación afecta la provisión de agua para consumo y riego, aumentando la demanda y, por ende, la competencia y los conflictos.

5.3. Actores Ligados al Conflicto y su Influencia
Diversos actores están involucrados en los conflictos del paisaje de Ambuqui, y sus roles e influencias son complejos. Entre los actores clave se encuentran las Juntas de Agua (San Clemente, Pueblo Viejo, La Yunguilla, Consumo Rumipamba, Riego Rumipamba, Riego Chaguarpamba, Consumo), el GAD Parroquial de Ambuqui, la Prefectura de Imbabura, el MAG (Ministerio de Agricultura y Ganadería), el MAATE (Ministerio de Ambiente, Agua y Transición Ecológica), EMAPA, Asoprovalle, Coop. Agrícola Ambuqui, Infraestructura Hotelera, Aso. Tuneros de Juncal, Aso. Ambuko, Coop. Agrícola La Esperanza, Agrocalidad, Unión Cochapamba, Aso. de Productores San Guillermo, Comuna Peñaherrera, UCIGMA (Unión de Comunidades Indígenas de Mariano Acosta) e IEDECA (Instituto de Ecología y Desarrollo de las Comunidades Andinas).
El impacto de los conflictos en los actores es predominantemente negativo. Por ejemplo, EMAPA experimenta problemas de abastecimiento de agua de consumo, lo que obliga a la población a comprar agua embotellada y genera una falta de comunicación oportuna. El GAD Parroquial de Ambuqui enfrenta Presión social por necesidades incumplidas debido a la falta de recursos económicos. El MAATE se ve envuelto en conflictos por permisos para el aprovechamiento de recursos naturales. Las Juntas de Agua sufren la Reducción de los caudales del agua de riego, lo que causa problemas en la distribución. Las Comunas experimentan la Reducción de las áreas boscosas y páramos, lo que afecta la provisión de agua. Los Bomberos enfrentan la necesidad de más recursos económicos para atender incendios forestales. El MAG (Ministerio de Agricultura y Ganadería) se enfrenta a un mayor riesgo de incumplimiento por las aseguradoras a los productores debido a los riesgos climáticos. La incapacidad de actores clave como el GAD Parroquial y EMAPA para cumplir sus funciones o coordinar eficazmente exacerba los conflictos.
La influencia de los actores en los conflictos varía. EMAPA y MAG tienen una influencia neutra, implicando movilización de recursos para mitigar amenazas o asegurar cultivos. El GAD Parroquial de Ambuqui tiene una influencia negativa debido a la Falta de gestión para la obtención de más recursos. El MAATE tiene una influencia positiva, al regular y controlar el aprovechamiento de los recursos hídricos y realizar campañas de conservación y reforestación. Las Juntas de Agua ejercen una influencia positiva a través del Mejoramiento de la infraestructura de distribución del agua mediante mingas. Los Bomberos también tienen una influencia positiva al Abastecer de agua para el consumo diario en época de sequía y contribuir a sofocar los incendios forestales. Las Comunas demuestran una influencia positiva a través de la Unión de las comunidades por medio de convocatorias para enfrentar alguna problemática.
El mapeo de actores por poder e interés revelaría desequilibrios de poder e intereses divergentes que moldean los resultados de la gobernanza. Por ejemplo, la Prefectura de Imbabura tiene un poder de 9 y un interés de 8, indicando una alta capacidad de influencia. Las Juntas de Agua y Comunas tienen un poder de 3 a 8 y un interés de 7 a 10, lo que las posiciona como actores clave con alto interés en la gestión del agua y los recursos. El GAD Parroquial de Ambuqui, con un poder de 7 y un interés de 3, muestra un alto poder pero un interés relativamente bajo, lo que podría explicar la Falta de gestión observada en los conflictos. Las relaciones entre actores son complejas, con algunos colaborando (por ejemplo, Junta de Agua San Clemente con Prefectura de Imbabura) y otros en conflicto (por ejemplo, Junta de Agua San Clemente con Junta de Agua Pueblo Viejo).

5.4. Mapeo y Relación de Niveles de Conflicto con Cooperación y Vulnerabilidades
El mapeo del alcance y tipo de conflictos permitiría visualizar las áreas geográficas donde se concentran los diferentes tipos de disputas (por ejemplo, Competencia por recursos naturales, Marginalización, tensión comunitaria o disturbios sociales) y su nivel de severidad (leve, moderado, grave). Esto revelaría que los conflictos severos a menudo coinciden espacialmente con áreas de alta dependencia de recursos y degradación ambiental. Por ejemplo, las zonas afectadas por la Sequía (Zona Alta y Baja), que impacta a un gran número de familias, también son focos de Competencia por recursos naturales con nivel grave o moderado.
La relación entre los niveles de conflicto y los niveles de cooperación/diferencias es dinámica. La línea de tiempo de conflictos muestra que, incluso en áreas de alta conflictividad, la cooperación puede surgir de necesidades compartidas o de la intervención de actores externos. Sin embargo, esta cooperación a menudo es frágil y puede deteriorarse rápidamente si no se abordan las causas subyacentes de las diferencias, como los Conflictos entre directivas de juntas de agua o los Intereses personales.
Los niveles de conflicto también se relacionan directamente con las vulnerabilidades de cada medio de vida. Los medios de vida que dependen de servicios ecosistémicos amenazados, como los cultivos que requieren agua en zonas de sequía, son más propensos a experimentar conflictos por recursos. La Sequía y la Contaminación basurero, que impactan a cientos de familias y afectan múltiples dimensiones de la seguridad humana, también son las amenazas que generan los conflictos más graves y extendidos. Esto subraya cómo la degradación ambiental y la escasez de recursos exacerban las vulnerabilidades de los medios de vida y, a su vez, alimentan las tensiones sociales.

6. Cascada de Impactos: Síntesis de Relaciones
6.1. Visualización de Relaciones Clave
El análisis integral del paisaje de Ambuqui revela una compleja red de interrelaciones entre los ecosistemas, los servicios ecosistémicos, los medios de vida, las amenazas, los impactos en la seguridad humana y los conflictos. Esta intrincada "cascada de impactos" demuestra que los problemas en una esfera se propagan y amplifican en otras, creando un ciclo de vulnerabilidad y tensión.
En el núcleo de esta cascada se encuentran los ecosistemas del paisaje, como el Páramo, el Bosque montano y el Bosque espinozo. Estos ecosistemas, aunque en su mayoría en un estado de funcionalidad moderada o incluso poco funcional en el caso del Matorral interandino, son la fuente de servicios ecosistémicos vitales. La provisión de agua (P3), alimentos (P1), regulación de la fertilidad del suelo (R5) y polinización (R6) son ejemplos críticos que sustentan directamente los medios de vida locales, desde la agricultura de Maíz, Trigo y Arveja hasta la ganadería y el Turismo comunitario. El agua, en particular, emerge como un nodo central en esta cascada, ya que su escasez o contaminación desencadena impactos en todas las dimensiones de la seguridad y alimenta la mayoría de los conflictos.
Sin embargo, estos ecosistemas y sus servicios están bajo la presión constante de diversas amenazas, tanto climáticas como no climáticas. La Sequía y el Desbordamiento de río son amenazas climáticas significativas, mientras que las Quemas, el Cambio de uso de suelo, la Contaminación basurero y el Uso inadecuado de agroquímicos son amenazas no climáticas prominentes. Estas amenazas, a menudo interconectadas y con tendencias crecientes, provocan impactos severos y multidimensionales en la seguridad humana. La Sequía, por ejemplo, no solo causa pérdida total de ingresos económicos y escasez generalizada de alimentos, sino que también genera Conflictos por el recurso agua. La Contaminación basurero afecta la seguridad sanitaria y ambiental, y desencadena Conflictos locales con las autoridades.
Estos impactos en la seguridad, a su vez, alimentan y exacerban los conflictos. La Competencia por recursos naturales, la Falta de comunicación y colaboración entre actores, las Instituciones frágiles o ineficientes y la Marginalización, tensión comunitaria o disturbios sociales son tipos de conflictos directamente vinculados a las amenazas y sus impactos. La evolución de los conflictos en Ambuqui ilustra una transición de la cooperación inicial, impulsada por necesidades compartidas, a la fragmentación y la disputa, exacerbadas por la escasez de recursos y las deficiencias en la gobernanza.
Este sistema se caracteriza por bucles de retroalimentación que se refuerzan mutuamente, creando un ciclo de degradación ambiental, vulnerabilidad de los medios de vida y conflicto social. Las prácticas insostenibles de los medios de vida (por ejemplo, la expansión agrícola, las quemas) degradan los ecosistemas y sus servicios. Esta degradación, a su vez, hace que los medios de vida sean más susceptibles a las amenazas climáticas y no climáticas, lo que conduce a impactos más severos y, potencialmente, a la continuación de prácticas insostenibles. La debilidad en la gobernanza local y la falta de atención oportuna por parte de las autoridades contribuyen a la persistencia y escalada de estos conflictos, que a su vez socavan la capacidad de la comunidad para gestionar sus recursos y adaptarse a los cambios. La interconexión entre el uso de agroquímicos, la contaminación del agua y la salud pública es un ejemplo claro de cómo las fallas en la gestión ambiental se traducen directamente en crisis de salud y conflictos.

7. Gobernanza en el Paisaje de Ambuqui
La gobernanza en Ambuqui es un factor crítico que influye en la resiliencia del paisaje frente a las amenazas y en la capacidad de las comunidades para gestionar los recursos y resolver conflictos.

7.1. Aspectos de Gobernanza: Confianza, Nivel de Organización y Participación
Aunque los datos directos de encuestas sobre confianza, organización y participación no se proporcionan en detalle, la información sobre conflictos y espacios de diálogo permite inferir ciertos aspectos. La presencia de conflictos como la Falta de comunicación y colaboración entre actores y la Poca participación, falta de comunicación en espacios formales sugiere que los niveles de organización y participación no son óptimos en todas las esferas. La Debilidad en la gobernanza local se identifica como un impacto político de amenazas como las Quemas y la Sequía, lo que indica una falta de confianza o capacidad en las estructuras de gobernanza existentes. Sin embargo, la Firma de acuerdos compromiso en la resolución de conflictos relacionados con el vertedero y la Participación de mingas comunitarias en la gestión del agua demuestran que, en ciertos contextos, la cooperación y la organización comunitaria pueden activarse, lo que sugiere una capacidad latente de autoorganización.

7.2. Redes de Actores y Espacios de Diálogo
El paisaje de Ambuqui cuenta con una compleja red de actores que interactúan, tanto en colaboración como en conflicto. Actores comunitarios como las Juntas de Agua y Asoprovalle colaboran con instituciones gubernamentales como la Prefectura de Imbabura, el MAG y Agrocalidad. Sin embargo, también existen conflictos entre actores, como las disputas entre la Junta de Agua San Clemente y la Junta de Agua Pueblo Viejo. Esta dualidad en las relaciones de los actores refleja la complejidad de la gobernanza local, donde los intereses pueden alinearse o divergir dependiendo del tema.
Existen diversos espacios de diálogo y coordinación, tanto formales como informales. Asoprovalle y la Unión de organización campesino de Cochapamba son ejemplos de espacios formales con alcance nacional o de paisaje, que apoyan la comercialización de productos y el mejoramiento vial. Sus fortalezas incluyen Alta producción y calidad y mercado seguro para Asoprovalle, y participación de los representantes de todas las comunidades para la Unión de organización campesino. Sin embargo, también presentan debilidades como el Desconocimiento del manejo del cultivo o la Poca participación, falta de comunicación.
Los espacios informales, como el Comité local de salud y las Asambleas del Agua, operan a nivel local. El Comité de Salud detecta problemas de salud y ambiente, y las Asambleas del Agua organizan mingas y cobran tasas de agua. Sus fortalezas incluyen la detección temprana de problemas de salud y un alto nivel organizativo y alta participación respectivamente. Sin embargo, carecen de recursos económicos o enfrentan Incumplimiento de los pagos y falta de rendimiento de cuentas. La coexistencia de espacios formales e informales, con sus respectivas fortalezas y debilidades, indica que la gobernanza en Ambuqui es un mosaico de estructuras que, aunque pueden facilitar la colaboración, también enfrentan desafíos en su efectividad y sostenibilidad.

7.3. Mapeo de Actores (Poder/Interés) y Relaciones
El mapeo de actores según su poder e interés revela la dinámica de influencia en el paisaje. Actores como la Prefectura de Imbabura (poder 9, interés 8), Agrocalidad (poder 7, interés 8) y Aso. Ambuko (poder 8, interés 7) poseen un alto poder e interés. Otros, como las Juntas de Agua (poder 3-9, interés 7-10), tienen un alto interés en la gestión del agua, aunque su poder puede variar. En contraste, la Infraestructura Hotelera (poder 2, interés 2) tiene un poder e interés bajos.
Las relaciones entre estos actores se definen por su posición en la matriz de poder/interés. Aquellos con alto poder e interés, como la Prefectura, son actores clave a involucrar y mantener cerca. Los actores con alto interés pero bajo poder podrían ser mantenidos informados o involucrados a través de mecanismos de participación. Los desequilibrios de poder y los intereses divergentes entre los actores influyen significativamente en la toma de decisiones y la resolución de conflictos. Por ejemplo, la Prefectura de Imbabura tiene un alto poder, lo que le permite influir en la gestión de recursos, pero su interacción con las Juntas de Agua puede generar tensiones si los intereses no se alinean.

7.4. Impacto de Conflictos en Actores y Relaciones, Oportunidades y Barreras para la Confianza
Los conflictos tienen un impacto negativo en los actores y sus relaciones, erosionando la confianza y debilitando las estructuras de gobernanza. Actores como EMAPA y el GAD Parroquial de Ambuqui sufren una presión social por necesidades incumplidas y problemas de abastecimiento, lo que afecta su legitimidad y capacidad operativa. Las Juntas de Agua y las Comunas también experimentan impactos negativos, como la Reducción de los caudales del agua y la Reducción de las áreas boscosas, lo que genera problemas en la distribución y provisión de recursos. La incapacidad de las instituciones clave para cumplir con sus roles o coordinar eficazmente exacerba los conflictos.
A pesar de los desafíos, existen oportunidades para la construcción de confianza entre los actores en conflicto. La Firma de acuerdos compromiso en la resolución de la problemática del vertedero y la Participación de mingas comunitarias con apoyo de ONGs en la gestión del agua demuestran que la cooperación es posible cuando hay una Necesidad de agua o una Unión de la población por necesidad. El MAATE y los Bomberos ejercen una influencia positiva en los conflictos al regular recursos y proveer ayuda en emergencias. Las Comunas también demuestran capacidad de Unión para enfrentar problemáticas.
Sin embargo, persisten barreras significativas. La Falta de comunicación y colaboración entre actores, la Pugna en la administración, los Intereses personales, la Falta de mantenimiento de infraestructura y la Falta de gestión del GAD parroquial son factores que dificultan la construcción de confianza y la resolución sostenible de conflictos. La construcción de confianza requiere abordar las causas fundamentales de los conflictos, como la escasez de recursos y las fallas de gobernanza, y fomentar espacios de diálogo inclusivos y transparentes que permitan la participación equitativa de todos los actores.

8. Capacidad Adaptativa
La capacidad adaptativa en el paisaje de Ambuqui se manifiesta a través de las respuestas de las comunidades y las instituciones frente a las amenazas, aunque con limitaciones estructurales y de recursos.

8.1. Niveles Relativos de Capacidad Adaptativa
Aunque los promedios numéricos y los niveles relativos de capacidad adaptativa (baja-intermedia-alta) no se proporcionan directamente en los datos, se pueden inferir aspectos cualitativos. La existencia de deficiente infraestructura y falta de mantenimiento para el acceso al agua y la falta de asesoría y manejo técnico para servicios como la polinización sugieren que la capacidad adaptativa se ve limitada por déficits de infraestructura y técnicos. Estos factores restringen directamente la capacidad de las comunidades para adaptarse eficazmente a las amenazas.
A pesar de estas limitaciones, las comunidades demuestran una base de capacidad adaptativa a través de iniciativas de autoorganización. Las Mingas de reforestación y la Creación de juntas de agua son ejemplos de acciones colectivas que, aunque a veces enfrentan Costos altos de los insumos, representan esfuerzos comunitarios para gestionar los recursos y responder a los desafíos. Esto indica que las comunidades poseen una base de agencia y organización que puede ser un pilar para fortalecer la capacidad adaptativa general.

8.2. Niveles por Dimensión (Necesidades Básicas, Innovación, Acción)
En la dimensión de Necesidades Básicas, los impactos de amenazas como la Sequía y la Contaminación basurero en la seguridad alimentaria, hídrica y económica indican desafíos persistentes en la satisfacción de las necesidades fundamentales de la población. La Escasez generalizada de alimentos y la Reducción del acceso a la canasta básica son claros indicadores de estas dificultades.
En cuanto a la Innovación, la falta de asesoría y manejo técnico y los costos altos de los insumos para riego tecnificado sugieren barreras significativas para la adopción de nuevas prácticas y tecnologías. Si bien hay iniciativas como el riego tecnificado, su implementación se ve obstaculizada por factores económicos y de conocimiento.
La dimensión de Acción es donde se observa una mayor fortaleza a nivel comunitario. La participación de mingas comunitarias y la unión de las comunidades por medio de convocatorias para enfrentar problemáticas demuestran la capacidad de las comunidades para movilizarse y tomar acciones colectivas. Sin embargo, la La falta de gestión del GAD parroquial indica una brecha en la acción institucional, lo que sugiere que, si bien las comunidades están dispuestas a actuar, la respuesta institucional no siempre es oportuna o suficiente. Esto resalta disparidades en la capacidad adaptativa, donde la agencia comunitaria es fuerte, pero las limitaciones en las necesidades básicas y la innovación persisten debido a factores externos y de gobernanza.

8.3. Contextualización de Respuestas con Comentarios de la Encuesta
Los comentarios cualitativos asociados a los impactos de las amenazas ofrecen una contextualización profunda de las respuestas y vulnerabilidades. Por ejemplo, ante la Sequía, la observación de Pocos casos de problemas de salud en el ámbito respiratorio sugiere una cierta resiliencia o adaptación en ese aspecto, o que los impactos no son tan agudos como en otras dimensiones. Sin embargo, la Percepción de inseguridad por desconocimiento del inicio de las quemas revela una vulnerabilidad psicológica y de información que afecta la seguridad personal. La Presencia de roedores en cultivos y hogares y los Problemas frecuentes de salud como problemas gastrointestinales asociados a la Contaminación basurero ilustran las consecuencias directas de la falta de gestión de residuos y la necesidad de respuestas sanitarias urgentes. Estos comentarios cualitativos son cruciales para comprender la experiencia humana de las amenazas y las estrategias de afrontamiento, así como las brechas en la capacidad adaptativa.

9. Conclusiones y Consideraciones Estratégicas
El análisis del paisaje de Ambuqui revela un sistema socioecológico complejo y dinámico, donde la interconexión entre ecosistemas, medios de vida, amenazas, seguridad humana y conflictos es profunda y, a menudo, se refuerza mutuamente.
Los ecosistemas de Ambuqui, aunque en su mayoría en un estado de funcionalidad moderada, son la base de los medios de vida locales, proporcionando servicios esenciales como agua, alimentos y regulación del suelo. Sin embargo, están bajo una presión considerable debido a actividades humanas como la expansión agrícola, las quemas y el uso de agroquímicos, así como por factores climáticos como la sequía. La degradación de estos ecosistemas no es un problema aislado, sino que tiene un impacto directo y en cascada en los medios de vida de la población, muchos de los cuales dependen de la agricultura a pequeña escala y de tenencias de tierra informales, lo que aumenta su vulnerabilidad.
Las amenazas, tanto climáticas (sequía, desbordamiento de ríos) como no climáticas (quemas, contaminación por residuos, cambio de uso de suelo), provocan una erosión multidimensional de la seguridad humana. La seguridad económica, alimentaria, sanitaria, ambiental, personal, comunitaria y política se ven afectadas simultáneamente. La sequía, en particular, emerge como la amenaza más generalizada y creciente, impactando a un gran número de familias y exacerbando la competencia por recursos vitales, especialmente el agua. La contaminación, por su parte, genera problemas de salud agudos y conflictos localizados.
Estos impactos en la seguridad son un motor clave de los conflictos en el paisaje. La escasez de recursos y la degradación ambiental alimentan directamente las disputas, transformando una historia de cooperación basada en necesidades compartidas en una de fragmentación y tensión. Las debilidades en la gobernanza local, incluyendo la falta de comunicación, la pugna administrativa y la ineficiencia institucional, son factores que perpetúan y escalan estos conflictos, a pesar de los esfuerzos de cooperación comunitaria. La migración forzada se perfila como una consecuencia potencial de estos impactos compuestos.
La gobernanza en Ambuqui es un mosaico de actores y espacios de diálogo, con fortalezas en la organización comunitaria para acciones específicas, pero con debilidades en la coordinación interinstitucional y la atención oportuna a las problemáticas. Los desequilibrios de poder y los intereses divergentes entre los actores influyen en la capacidad de respuesta del paisaje. La capacidad adaptativa se ve limitada por déficits de infraestructura y técnicos, aunque la agencia y la movilización comunitaria demuestran una base de resiliencia.
En síntesis, el paisaje de Ambuquí se encuentra atrapado en un ciclo de retroalimentación negativa donde la degradación ambiental impulsa la inseguridad de los medios de vida, lo que a su vez puede conducir a conflictos y una mayor degradación. El agua es el elemento central de esta cascada, cuya escasez o contaminación desencadena la mayoría de los impactos y conflictos. Para romper este ciclo, es imperativo un enfoque integrado que no solo aborde la conservación de los ecosistemas, sino que también fortalezca la gobernanza, promueva prácticas de medios de vida sostenibles, invierta en infraestructura resiliente y desarrolle la capacidad adaptativa de las comunidades, con especial atención a las vulnerabilidades diferenciadas por género y a la seguridad hídrica.

Análisis de la Capacidad Adaptativa en el Paisaje de Ambuqui: Dimensiones, Niveles y Contextualización

I. Resumen Ejecutivo
Este informe presenta un análisis exhaustivo de la capacidad adaptativa en el paisaje de Ambuqui, Ecuador, con base en datos recopilados a través de encuestas detalladas. La evaluación se estructura en tres dimensiones fundamentales: Necesidades Básicas, Innovación y Acción, proporcionando una comprensión matizada de la resiliencia de las comunidades frente a los desafíos ambientales y socioeconómicos.
Los resultados indican que la capacidad adaptativa general en Ambuqui exhibe una variabilidad significativa entre las diferentes zonas geográficas (Zona Alta, Zona Media y Zona Baja). Si bien algunas áreas demuestran una capacidad intermedia a alta en ciertas dimensiones, otras revelan vulnerabilidades críticas que requieren atención prioritaria. Por ejemplo, se observa que la satisfacción de las necesidades básicas está intrínsecamente ligada a la salud de los ecosistemas, donde la degradación ambiental puede impactar directamente la seguridad alimentaria y los ingresos. La capacidad de innovación, aunque presente, se ve a menudo como una respuesta reactiva a las amenazas, y su implementación está condicionada por el acceso a recursos y asistencia técnica. Finalmente, la capacidad de acción colectiva se encuentra fuertemente influenciada por los niveles de confianza en las instituciones y la prevalencia de conflictos, especialmente aquellos relacionados con los recursos naturales.
Las principales conclusiones destacan la interconexión de estas dimensiones, sugiriendo que las deficiencias en un área pueden comprometer la fortaleza en otras. Las recomendaciones estratégicas se centran en enfoques integrados que no solo aborden las carencias en necesidades básicas, sino que también fomenten la innovación contextualizada y fortalezcan el capital social a través de la construcción de confianza y la resolución de conflictos. El informe subraya la necesidad de intervenciones diferenciadas, adaptadas a las realidades específicas de cada zona y grupo demográfico dentro del paisaje de Ambuqui.

II. Introducción a la Capacidad Adaptativa en el Contexto del Paisaje
La capacidad adaptativa representa la habilidad de un sistema, ya sea una comunidad, un ecosistema o un paisaje, para ajustarse a los cambios, moderar los daños potenciales, aprovechar las oportunidades o hacer frente a las consecuencias de los eventos adversos. En el contexto de los sistemas socio-ecológicos, esta capacidad es un pilar fundamental para la resiliencia, permitiendo a las comunidades persistir y prosperar frente a la variabilidad climática, las amenazas ambientales y las presiones socioeconómicas. La naturaleza multidimensional de la capacidad adaptativa reconoce que la resiliencia no es un atributo singular, sino una compleja interacción de factores que abarcan desde la disponibilidad de recursos básicos hasta la gobernanza y la capacidad de aprendizaje.
La evaluación de la capacidad adaptativa es de vital importancia para el paisaje de Ambuqui. Esta región se caracteriza por una diversidad de ecosistemas, que incluyen el Bosque Montano, el Páramo, el Matorral Interandino y el Bosque Espinozo, así como las Riveras del Río. Estos ecosistemas sustentan una variedad de medios de vida, desde la producción de maíz, trigo y arveja en la Zona Alta, hasta el cultivo de mango, aguacate y limón en la Zona Media y Baja, e incluso el turismo comunitario y la artesanía. Sin embargo, el paisaje de Ambuqui está expuesto a diversas amenazas climáticas y no climáticas, como sequías, quemas, desbordamientos de ríos y contaminación. La comprensión de la capacidad adaptativa de las comunidades en este contexto es esencial para diseñar intervenciones que fortalezcan su resiliencia y promuevan un desarrollo sostenible.
El enfoque metodológico para este análisis se basa en la evaluación de la capacidad adaptativa a través de tres dimensiones clave: Necesidades Básicas, Innovación y Acción, tal como se especifica en el Paso 9 del documento "Análisis de datos (mapeo participativo)". Los datos primarios para esta evaluación provienen de la "Encuesta capacidad adaptativa" (Herramienta 7.1 Cuestionario). Las respuestas de la encuesta, que a menudo se presentan en rangos porcentuales (por ejemplo, "0-20", "40-60"), se transformaron a sus puntos medios (por ejemplo, 10, 50) para permitir un análisis numérico. Los valores "N/A" (no aplica) se trataron como datos faltantes y se excluyeron de los cálculos promedio para evitar sesgos. La contextualización de las respuestas se realizó utilizando los comentarios cualitativos disponibles en los datos de la encuesta, lo que permitió una comprensión más profunda de los factores subyacentes a los valores numéricos.
La selección de las dimensiones de "Necesidades Básicas", "Innovación" y "Acción" para evaluar la capacidad adaptativa refleja una comprensión integral de la resiliencia. Este marco reconoce que la capacidad de una comunidad para ajustarse a los cambios o mitigar sus consecuencias no depende únicamente de la satisfacción de sus necesidades fundamentales, sino también de su habilidad para generar soluciones novedosas y para implementarlas de manera colectiva. Una capacidad adaptativa robusta se caracteriza por un alto desempeño en las tres áreas. Por ejemplo, si las necesidades básicas no están adecuadamente cubiertas, como la estabilidad de los ingresos o la seguridad alimentaria, la capacidad de innovación puede verse severamente limitada. De manera similar, incluso las ideas más innovadoras podrían no materializarse en acciones efectivas sin una fuerte organización comunitaria y confianza en los mecanismos de apoyo mutuo. Esto sugiere una relación sinérgica donde las deficiencias en un área pueden socavar las fortalezas en otras, creando un paisaje adaptativo complejo donde las vulnerabilidades pueden propagarse entre las dimensiones.
`;
